package ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import model.User;

/**
 *
 * @author otibhoedeoghon
 */
public class RegistrationJPanel extends javax.swing.JPanel {

    private ViewJPanel viewPanel;
    private javax.swing.JPanel cardContainer;

    /**
     * Creates new form RegistrationJPanel
     */
    public RegistrationJPanel() {
        initComponents();
    }

    public void setViewPanel(ViewJPanel viewPanel) {
        this.viewPanel = viewPanel;
    }

    public void setCardContainer(javax.swing.JPanel cardContainer) {
        this.cardContainer = cardContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailTextField = new javax.swing.JTextField();
        continentComboBox = new javax.swing.JComboBox<>();
        email = new javax.swing.JLabel();
        experience = new javax.swing.JLabel();
        GenderComboBox = new javax.swing.JComboBox<>();
        Age = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        firstnameTextField = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        photoTextField = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        UploadPhoto = new javax.swing.JButton();
        College = new javax.swing.JLabel();
        photoUpload = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        textPhoneNumber = new javax.swing.JFormattedTextField();
        Name1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCalendarComboBox1 = new de.wannawork.jcalendar.JCalendarComboBox();

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Australia" }));

        email.setText("Email:");

        experience.setText("Experience:");

        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        Age.setText("Age:");

        Photo.setText("Photo:");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());

        photoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoTextFieldActionPerformed(evt);
            }
        });

        Name.setText("First Name:");

        UploadPhoto.setText("Upload Photo");
        UploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPhotoActionPerformed(evt);
            }
        });

        College.setText("Gender:");

        PhoneNumber.setText("Phone:");

        try {
            textPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textPhoneNumber.setToolTipText("123-456-7890");
        textPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPhoneNumberActionPerformed(evt);
            }
        });

        Name1.setText("Last Name:");

        jLabel1.setText("Continent:");

        jLabel2.setText("Date of Birth:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(Submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Photo)
                            .addComponent(Name1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UploadPhoto))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(firstnameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(lastnameTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneNumber)
                                    .addComponent(experience)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(email)
                                        .addComponent(College))
                                    .addComponent(Age)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(emailTextField)
                                                .addComponent(textPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(Name))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCalendarComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(College)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experience)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Photo)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadPhoto))
                .addGap(18, 18, 18)
                .addComponent(photoUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        String errorTitle = "Ooops";
 
        try {
            String firstName = firstnameTextField.getText();
            String lastName = lastnameTextField.getText();
            int age = (int) jSpinner1.getValue();
            String gender = (String) GenderComboBox.getSelectedItem();
            String phone = textPhoneNumber.getText();
            String email = emailTextField.getText().trim();
            String continent = (String) continentComboBox.getSelectedItem();
            String experience = jTextArea1.getText();
            String photoPath = photoTextField.getText();
 
            // Validate first name
            if (firstName == null || firstName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Invalid First Name Provided", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Validate last name
            if (lastName == null || lastName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Invalid Last Name Provided", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Validate phone
            if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Invalid Phone Number", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Validate age
            if (age < 18) {
                JOptionPane.showMessageDialog(this, "You must be at least 18 years old", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Validate email
            if (email == null || email.isEmpty() || !email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
                JOptionPane.showMessageDialog(this, "Invalid Email Provided", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Validate date of birth
            // >>> CHANGED: was jDateChooser1.getDate();  (line 244 — this caused the crash)
            // The date picker on this form is a JCalendarComboBox named jCalendarComboBox1.
            java.util.Date dob = jCalendarComboBox1.getDate();
            // NOTE: JCalendarComboBox starts with today's date, so dob is normally never null.
            // The check is kept as a safety net.
            if (dob == null) {
                JOptionPane.showMessageDialog(this, "Please select a Date of Birth", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // >>> ADDED: reject future dates (otherwise the age check reports "expected age: -1")
            if (dob.after(new java.util.Date())) {
                JOptionPane.showMessageDialog(this, "Date of Birth cannot be in the future", errorTitle, ERROR_MESSAGE);
                return;
            }
 
            int computedAge = calculateAge(dob);
            if (computedAge != age) {
                JOptionPane.showMessageDialog(this,
                    "Date of Birth does not match the Age entered (expected age: " + computedAge + ")",
                    errorTitle, ERROR_MESSAGE);
                return;
            }
 
            // Build the photo File (if one was uploaded)
            File photoFile = (photoPath != null && !photoPath.trim().isEmpty())
            ? new File(photoPath.trim())
            : null;
 
            // === Create User object ===
            User user = new User(firstName.trim(), lastName.trim(), gender, age,
                phone, email, continent, experience, photoFile, dob);
 
            // Build the photo icon (if one was uploaded)
            ImageIcon photoIcon = null;
            if (photoFile != null) {
                ImageIcon rawIcon = new ImageIcon(photoFile.getAbsolutePath());
                Image scaled = rawIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                photoIcon = new ImageIcon(scaled);
            }
 
            // === Show success popup using user.toString() ===
            JOptionPane.showMessageDialog(
                this,
                user.toString(),
                "Success",
                JOptionPane.INFORMATION_MESSAGE,
                photoIcon
            );
 
            // Switch to the view panel and show the submitted user
            System.out.println("viewPanel=" + viewPanel + " cardContainer=" + cardContainer);
 
            if (viewPanel != null && cardContainer != null) {
                viewPanel.displayUser(user);
                CardLayout cl = (CardLayout) cardContainer.getLayout();
                cl.show(cardContainer, "view");
                cardContainer.revalidate();
                cardContainer.repaint();
            }
 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Age Provided", errorTitle, ERROR_MESSAGE);
        }
    }                                      
 
    // >>> CHANGED: rewritten with java.time.
    // The old version compared DAY_OF_YEAR, which is off by one around birthdays
    // when one of the years is a leap year (e.g. born March 1, 2004).
    private int calculateAge(java.util.Date dob) {
        java.time.LocalDate birth = dob.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
        return java.time.Period.between(birth, java.time.LocalDate.now()).getYears();
    
    
    }//GEN-LAST:event_SubmitActionPerformed

    private void photoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextFieldActionPerformed

    }//GEN-LAST:event_photoTextFieldActionPerformed

    private void UploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPhotoActionPerformed

       JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            photoTextField.setText(selectedFile.getAbsolutePath());

            // Load and scale image to fit label
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = icon.getImage().getScaledInstance(photoUpload.getWidth(), photoUpload.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledImage);

            photoUpload.setIcon(icon);
            photoUpload.setText(""); // remove placeholder text
        }
             
    }//GEN-LAST:event_UploadPhotoActionPerformed

    private void textPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhoneNumberActionPerformed

        String phone = textPhoneNumber.getText();
        if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number (e.g., 123-456-7890)",
                "Invalid Phone", ERROR_MESSAGE);
            textPhoneNumber.requestFocus();
        }
    }//GEN-LAST:event_textPhoneNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel College;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JLabel Photo;
    private javax.swing.JButton Submit;
    private javax.swing.JButton UploadPhoto;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel experience;
    private javax.swing.JTextField firstnameTextField;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JLabel photoUpload;
    private javax.swing.JFormattedTextField textPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
